export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAIL = "FETCH_POST_FAIL";
export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAIL = "FETCH_POSTS_FAIL";
export const FETCH_POST_COMMENTS_SUCCESS = "FETCH_POST_COMMENTS_SUCCESS";
export const FETCH_POST_COMMENTS_FAIL = "FETCH_POST_COMMENTS_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const ADD_A0_PROFILE = "ADD_PROFILE";
export const ADD_DB_PROFILE = "ADD_DB_PROFILE";
export const REMOVE_A0_PROFILE = "REMOVE_PROFILE";
