// Posts
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAIL = "FETCH_POST_FAIL";
export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAIL = "FETCH_POSTS_FAIL";
export const FETCH_PROFILE_POSTS_REQUEST = "FETCH_PROFILE_POSTS_REQUEST";
export const FETCH_PROFILE_POSTS_SUCCESS = "FETCH_PROFILE_POSTS_SUCCESS";
export const FETCH_PROFILE_POSTS_FAIL = "FETCH_PROFILE_POSTS_FAIL";
export const FETCH_POST_COMMENTS_SUCCESS = "FETCH_POST_COMMENTS_SUCCESS";
export const FETCH_POST_COMMENTS_FAIL = "FETCH_POST_COMMENTS_FAIL";
export const DELETE_POST_COMMENT_SUCCESS = "DELETE_POST_COMMENT_SUCCESS";
export const DELETE_POST_COMMENT_FAIL = "DELETE_POST_COMMENT_FAIL";
export const DELETE_POST_COMMENT_REQUEST = "DELETE_POST_COMMENT_REQUEST";
export const UPDATE_POST_COMMENT_REQUEST = "UPDATE_POST_COMMENT_REQUEST";
export const UPDATE_POST_COMMENT_FAIL = "UPDATE_POST_COMMENT_FAIL";
export const UPDATE_POST_COMMENT_SUCCESS = "UPDATE_POST_COMMENT_SUCCESS";
export const SET_COMMENT_EDITABLE = "SET_COMMENT_EDITABLE";
export const SUBMIT_POST_COMMENT_REQUEST = "SUBMIT_POST_COMMENT_REQUEST";
export const SUBMIT_POST_COMMENT_FAIL = "SUBMIT_POST_COMMENT_FAIL";
export const SUBMIT_POST_COMMENT_SUCCESS = "SUBMIT_POST_COMMENT_SUCCESS";
export const ADD_POST_FAIL = "ADD_POST_FAIL";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";

// Edits
export const FETCH_EDITS_REQUEST = "FETCH_EDITS_REQUEST";
export const FETCH_EDITS_SUCCESS = "FETCH_EDITS_SUCCESS";
export const FETCH_EDITS_FAIL = "FETCH_EDITS_FAIL";
export const FETCH_EDIT_SUCCESS = "FETCH_EDIT_SUCCESS";
export const FETCH_EDIT_FAIL = "FETCH_EDIT_FAIL";
export const ADD_EDIT_FAIL = "ADD_EDIT_FAIL";
export const ADD_EDIT_SUCCESS = "ADD_EDIT_SUCCESS";
export const DELETE_EDIT_REQUEST = "DELETE_EDIT_REQUEST";
export const DELETE_EDIT_SUCCESS = "DELETE_EDIT_SUCCESS";
export const DELETE_EDIT_FAIL = "DELETE_EDIT_FAIL";
export const UPDATE_EDIT_REQUEST = "UPDATE_EDIT_REQUEST";
export const UPDATE_EDIT_FAIL = "UPDATE_EDIT_FAIL";
export const UPDATE_EDIT_SUCCESS = "UPDATE_EDIT_SUCCESS";
export const LIKE_EDIT_REQUEST = "LIKE_EDIT_REQUEST";
export const LIKE_EDIT_FAIL = "LIKE_EDIT_FAIL";
export const LIKE_EDIT_SUCCESS = "LIKE_EDIT_SUCCESS";
export const UNLIKE_EDIT_REQUEST = "UNLIKE_EDIT_REQUEST";
export const UNLIKE_EDIT_FAIL = "UNLIKE_EDIT_FAIL";
export const UNLIKE_EDIT_SUCCESS = "UNLIKE_EDIT_SUCCESS";

// Auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const ADD_A0_PROFILE = "ADD_PROFILE";
export const ADD_DB_PROFILE = "ADD_DB_PROFILE";
export const REMOVE_A0_PROFILE = "REMOVE_PROFILE";

export const CHANGE_PROFILE_AVATAR_SUCCESS = "CHANGE_PROFILE_AVATAR_SUCCESS";
export const CHANGE_PROFILE_AVATAR_FAIL = "CHANGE_PROFILE_AVATAR_FAIL";
export const CHANGE_PROFILE_AVATAR_REQUEST = "CHANGE_PROFILE_AVATAR_REQUEST";

export const FETCH_PROFILE_LIKES_SUCCESS = "FETCH_PROFILE_LIKES_SUCCESS";
export const FETCH_PROFILE_LIKES_FAIL = "FETCH_PROFILE_LIKES_FAIL";
export const FETCH_PROFILE_LIKES_REQUEST = "FETCH_PROFILE_LIKES_REQUEST";
